const String anandSahibMeaningTitle =
    "Anand Sahib (Meaning) / ਅਨੰਦੁ ਸਾਹਿਬ ਅਰਥ";

const String anandSahibMeaningText = """
raamakalee mahalaa teejaa ana(n)dhu
Raamkalee, Third Mehla, Anand The Song Of Bliss:

ikOankaar satigur prasaadh ||
One Universal Creator God. By The Grace Of The True Guru:

ana(n)dh bhiaa meree maae satiguroo mai paiaa ||satigur ta paiaa sahaj setee man vajeeaa vaadhaieeaa || raag ratan paravaar pareeaa sabadh gaavan aaieeaa || sabadho ta gaavahu haree keraa man jinee vasaiaa || kahai naanak ana(n)dh hoaa satiguroo mai paiaa ||1||
I am in ecstasy, O my mother, for I have found my True Guru. I have found the True Guru, with intuitive ease, and my mind vibrates with the music of bliss.
The jewelled melodies and their related celestial harmonies have come to sing the Word of the Shabad. The Lord dwells within the minds of those who sing the Shabad. Says Nanak, I am in ecstasy, for I have found my True Guru. ||1||

e man meriaa too sadhaa rahu har naale || har naal rahu too ma(n)n mere dhookh sabh visaaranaa || a(n)geekaar oh kare teraa kaaraj sabh savaaranaa || sabhanaa galaa samarath suaamee so kiau manahu visaare || kahai naanak ma(n)n mere sadhaa rahu har naale ||2||
O my mind, remain always with the Lord. Remain always with the Lord, O my mind, and all sufferings will be forgotten. He will accept You as His own, and all your affairs will be perfectly arranged. Our Lord and Master is all-powerful to do all things, so why forget Him from your mind? Says Nanak, O my mind, remain always with the Lord. ||2||

saache saahibaa kiaa naahee ghar terai || ghar
ta terai sabh kichh hai jis dheh su paave || sadhaa sifat salaeh teree naam man vasaave || naam jin kai man vasiaa vaaje sabadh ghanere || kahai naanak sache saahib kiaa naahee ghar terai ||3||
O my True Lord and Master, what is there which is not in Your celestial home? Everything is in Your home; they receive, unto whom You give. Constantly singing Your Praises and Glories, Your Name is enshrined in the mind. The divine melody of the Shabad vibrates for those, within whose minds the Naam abides. Says Nanak, O my True Lord and Master, what is there which is not in Your home?||3||

saachaa naam meraa aadhaaro || saach naam adhaar meraa jin bhukhaa sabh gavaieeaa || kar saa(n)t sukh man aai vasiaa jin ichhaa sabhpujaieeaa || sadhaa kurabaan keetaa guroo viTahu jis dheeaa eh vaddiaaieeaa || kahai naanak sunahu sa(n)tahu sabadh dharahu piaaro || saachaa naam meraa aadhaaro ||4||
The True Name is my only support. The True Name is my only support; it satisfies all hunger. It has brought peace and tranquility to my mind; it has fulfilled all my desires. I am forever a sacrifice to the Guru, who possesses such glorious greatness. Says Nanak, listen, O Saints; enshrine love for the Shabad. The True Name is my only support. ||4|||

vaaje pa(n)ch sabadh tit ghar sabhaagai || ghar sabhaagai sabadh vaaje kalaa jit ghar dhaareeaa Il pa(n)ch dhoot tudh vas keete kaal ka(n)Tak maariaa || dhur karam paiaa tudh jin kau s naam har kai laage || kahai naanak teh sukh hoaa tit char anahadh vaaje ||5||
The Panch Shabad, the five primal sounds, vibrate in that blessed house. In that blessed house, the Shabad vibrates; He infuses His almighty power into it. Through You, we subdue the five demons of desire, and slay Death, the torturer. Those who have such pre-ordained destiny are attached to the Lord’s Name. Says Nanak, they are at peace, and the unstruck sound current vibrates within their homes.||5||

saachee livai bin dheh nimaanee || dheh nimaanee livai baajhahu kiaa kare vechaareeaa || tudh baajh samarath koi naahee kirapaa kar banavaareeaa || es nau hor thaau naahee sabadh laag savaareeaa || kahai naanak livai baajhahu kiaa kare vechaareeaa ||6||
Without the true love of devotion, the body is without honor. The body is dishonored without devotional love; what can the poor wretches do? No one except You is all-powerful; please bestow Your Mercy, O Lord of all nature. There is no place of rest, other than the Name; attached to the Shabad, we are embellished with beauty. Says Nanak, without devotional love, what can the poor wretches do?||6||

aana(n)dh aana(n)dh sabh ko kahai aana(n)dh guroo te jaaniaa || jaaniaa aana(n)dh sadhaa gur te kirapaa kare piaariaa || kar kirapaa kilavikh ka Te giaan a(n)jan saariaa || a(n)dharahu jin kaa moh tu Taa tin kaa sabadh sachai savaariaa || kahai naanak eh ana(n)dh hai aana(n)dh gur te jaaniaa ||7||
Bliss, bliss – everyone talks of bliss; bliss is known only through the Guru. Eternal bliss in known only through the Guru, when the Beloved Lord grants His Grace. Granting His Grace, He cuts away our sins; He blesses us with the healing ointment of spiritual wisdom. Those who eradicate attachment from within themselves, are adorned with the Shabad, the Word of the True Lord. Says Nanak, this alone is bliss – bliss which is known through the Guru. ||7||

baabaa jis too dheh soiee jan paavai || paavai ta so jan dheh jis no hor kiaa kareh vechaariaa || eik bharam bhoole fireh dheh dhis ik naam laag savaariaa || gur parasaadhee man bhiaa niramal jinaa bhaanaa bhaave || kahai naanak jis dheh piaare soiee jan paave ||8||
O Baba, he alone receives it, unto whom You give it. He alone receives it, unto whom You give it; what can the other poor wretched beings do? Some are deluded by doubt, wandering in the ten directions; some are adorned with attachment to the Naam. By Guru’s Grace, the mind becomes immaculate and pure, for those who follow God’s Will. Says Nanak, he alone receives it, unto whom You give it, 0 Beloved Lord. ||8||

aavahu sa(n)t piaariho akath kee kareh kahaanee|| kareh kahaanee akath keree kit dhuaarai paieeaai || tan man dhan sabh saup gur kau hukam ma(n)niaai paieeaai || hukam ma(n)nih guroo keraa gaavahu sachee baanee || kahai naanak sunahu sa(n)tahu kathih akath kahaanee ||9||
Come, Beloved Saints, let us speak the Unspoken Speech of the Lord. How can we speak the Unspoken Speech of the Lord? Through which door will we find Him? Surrender body, mind, wealth, and everything to the Guru; obey the Order of His Will, and you will find Him. Obey the Hukam of the Guru’s Command, and sing the True Word of His Bani. Says Nanak, listen, O Saints, and speak the Unspoken Speech of the Lord. ||9||

e man cha(n)chalaa chaturaiee kinai na paiaa || chaturaiee na paiaa kinai too sun ma(n)n meriaa || eh maiaa mohanee jin et bharam bhulaiaa || maiaa ta mohanee tinai keetee jin Thagaulee paieeaa || kurabaan keetaa tisai viTahu jin moh mee Thaa laiaa || kahai naanak man cha(n)chal chaturaiee kinai na paiaa ||10||
O fickle mind, through cleverness, no one has found the Lord. Through cleverness, no one has found Him; listen, O my mind. This Maya is so fascinating; because of it, people wander in doubt. This fascinating Maya was created by the One who has administered this potion. I am a sacrifice to the One who has made emotional attachment sweet. Says Nanak, O fickle mind, no one has found Him through cleverness. ||10||

e man piaariaa too sadhaa sach samaale || eh kuTa(n)b too j dhekhadhaa chalai naahee terai naale || saath terai chalai naahee tis naal kiau chit laieeaai || aaisaa ka(n)m moole na keechai jit a(n)t pachhotaieeaai || satiguroo kaa upadhes sun too hovai terai naale || kahai naanak man piaare too sadhaa sach samaale ||11||
O beloved mind, contemplate the True Lord forever. This family which you see shall not go along with you. They shall not go along with you, so why do you focus your attention on them? Don’t do anything that you will regret in the end. Listen to the Teachings of the True Guru – these shall go along with you. Says Nanak, O beloved mind, contemplate the True Lord forever. ||11||

agam agocharaa teraa a(n)t na paiaa || a(n)to na paiaa kinai teraa aapanaa aap too jaanahe || jeea ja(n)t sabh khel teraa kiaa ko aakh vakhaane || aakheh ta vekheh sabh toohai jin jagat upaiaa || kahai naanak too sadhaa aga(n)m hai teraa a(n)t na
paiaa ||12||
O inaccessible and unfathomable Lord, Your limits cannot be found. No one has found Your limits; only You Yourself know. All living beings and creatures are Your play; how can anyone describe You? You speak, and You gaze upon all; You created the Universe. Says Nanak, You are forever inaccessible; Your limits cannot be found. ||12||

sur nar mun jan a(n)mrit khojadhe su a(n)mrit gur te paiaa || paiaa a(n)mrit gur kirapaa keenee sachaa man vasaiaa || jeea ja(n)t sabh tudh upaae ik vekh parasan aaiaa || lab lobh aha(n)kaar chookaa satiguroo bhalaa bhaiaa || kahai naanak jis no aap tu Thaa tin a(n)mrit gur te paiaa ||13||
The angelic beings and the silent sages search for the Ambrosial Nectar; this Amrit is obtained from the Guru. This Amrit is obtained, when the Guru grants His Grace; He enshrines the True Lord within the mind. All living beings and creatures were created by You; only some come to see the Guru, and seek His blessing. Their greed, avarice and egotism are dispelled, and the True Guru seems sweet. Says Nanak, those with whom the Lord is pleased, obtain the Amrit, through the Guru. ||13||

bhagataa kee chaal niraalee || chaalaa niraalee bhagataeh keree bikham maarag chalanaa || lab lobh aha(n)kaar taj tirasanaa bahut naahee bolanaa || kha(n)niahu tikhee vaalahu nikee et maarag jaanaa || gur parasaadhee jinee aap tajiaa har vaasanaa samaanee || kahai naanak chaal bhagataa jugahu jug niraalee ||14||
The lifestyle of the devotees is unique and distinct. The devotees’ lifestyle is unique and distinct; they follow the most difficult path. They renounce greed, avarice, egotism and desire; they do not talk too much. The path they take is sharper than a two-edged sword, and finer than a hair. By Guru’s Grace, they shed their selfishness and conceit; their hopes are merged in the Lord. Says Nanak, the lifestyle of the devotees, in each and every age, is unique and distinct. ||14||

jiau too chalaieh tiv chaleh suaamee hor kiaa jaanaa gun tere || jiv too chalaieh tivai chaleh jinaa maarag paavahe || kar kirapaa jin naam laieh s har har sadhaa dhiaavahe || jis no kathaa sunaieh aapanee s gurdhuaarai sukh paavahe || kahai naanak sache saahib jiau bhaavai tivai chalaavahe ||15||
As You make me walk, so do I walk, O my Lord and Master; what else do I know of Your Glorious Virtues? As You cause them walk, they walk – You have placed them on the Path. In Your Mercy, You attach them to the Naam; they meditate forever on the Lord, Har, Har. Those whom You cause to listen to Your sermon, find peace in the Gurdwara, the Guru’s Gate. Says Nanak, O my True Lord and Master, you make us walk according to Your Will. ||15||

eh sohilaa sabadh suhaavaa || sabadho suhaavaa sadhaa sohilaa satiguroo sunaiaa || eh tin kai ma(n)n vasiaa jin dhurahu likhiaa aaiaa || eik fireh ghanere kareh galaa galee kinai na paiaa || kahai naanak sabadh sohilaa satiguroo sunaiaa ||16||
This song of praise is the Shabad, the most beautiful Word of God. This beauteous Shabad is the everlasting song of praise, spoken by the True Guru. This is enshrined in the minds of those who are so pre-destined by the Lord. Some wander around, babbling on and on, but none obtain Him by babbling. Says Nanak, the Shabad, this song of praise, has been spoken by the True Guru. ||16||

pavit hoe se janaa jinee har dhiaaiaa || har dhiaaiaa pavit hoe gurmukh jinee dhiaaiaa|| pavit maataa pitaa kuTa(n)b sahit siau pavit sa(n)gat sabaieeaa || kahadhe pavit sunadhe pavit se pavit jinee ma(n)n vasaiaa || kahai naanak se pavit jinee gurmukh har har dhiaaiaa ||17||
Those humble beings who meditate on the Lord become pure. Meditating on the Lord, they become pure; as Gurmukh, they meditate on Him. They are pure, along with their mothers, fathers, family and friends; all their companions are pure as well. Pure are those who speak, and pure are those who listen;
those who enshrine it within their minds are pure. Says Nanak, pure and holy are those who, as Gurmukh, meditate on the Lord, Har, Har. ||17||

karamee sahaj na uoopajai vin sahajai sahasaa na jai || neh jai sahasaa kitai sa(n)jam rahe karam kamaae || sahasai jeeau maleen hai kit sa(n)jam dhotaa jaae || ma(n)n dhovahu sabadh laagahu har siau rahahu chit lai || kahai naanak gur parasaadhee sahaj upajai ih sahasaa iv jai ||18||
By religious rituals, intuitive poise is not found; without intuitive poise, skepticism does not depart. Skepticism does not depart by contrived actions; everybody is tired of performing these rituals. The soul is polluted by skepticism; how can it be cleansed? Wash your mind by attaching it to the Shabad, and keep your consciousness focused on the Lord. Says Nanak, by Guru’s Grace, intuitive poise is produced, and this skepticism is dispelled. ||18||

jeeahu maile baaharahu niramal || baaharahu niramal jeeahu ta maile tinee janam jooaai haariaa || eh tisanaa vaddaa rog lagaa maran manahu visaariaa || vedhaa meh naam utam so suneh naahee fireh jiau betaaliaa || kahai naanak jin sach tajiaa kooRe laage tinee janam jooaai haariaa ||19||
Inwardly polluted, and outwardly pure. Those who are outwardly pure and yet polluted within, lose their lives in the gamble. They contract this terrible disease of desire, and in their minds, they forget about dying. In the Vedas, the ultimate objective is the Naam, the Name of the Lord; but they do not hear this, and they wander around like demons. Says Nanak, those who forsake Truth and cling to falsehood, lose their lives in the gamble. || 19||

jeeahu niramal baaharahu niramal || baaharahu ta niramal jeeahu niramal satigur te karanee kamaanee || kooR kee soi pahuchai naahee manasaa sach samaanee || janam ratan jinee khaTiaa bhale se vanajaare || kahai naanak jin ma(n)n niramal sadhaa raheh gur naale ||20|| Inwardly pure, and outwardly pure. Those who are outwardly pure and also pure within, through the Guru, perform good deeds. Not even an iota of falsehood touches them; their hopes are absorbed in the Truth. Those who earn the jewel of this human life, are the most excellent of merchants.
Says Nanak, those whose minds are pure, abide with the Guru forever. ||20||

je ko sikh guroo setee sanamukh hovai || hovai ta sanamukh sikh koiee jeeahu rahai gur naale || gur ke charan hiradhai dhiaae a(n)tar aatamai samaale || aap chhadd sadhaa rahai paranai gur bin avar na jaanai koe || kahai naanak sunahu sa(n)tahu so sikh sanamukh hoe ||21||
If a Sikh turns to the Guru with sincere faith, as sunmukh if a Sikh turns to the Guru with sincere faith, as sunmukh, his soul abides with the Guru. Within his heart, he meditates on the lotus feet of the Guru; deep within his soul, he contemplates Him. Renouncing selfishness and conceit, he remains always on the side of the Guru; he does not know anyone except the Guru. Says Nanak listen, O Saints: such a Sikh turns towards the Guru with sincere faith, and becomes sunmukh. ||21||

je ko gur te vemukh hovai bin satigur mukat na paavai || paavai mukat na hor thai koiee puchhahu bibekeeaa jaae || anek joonee bharam aavai vin satigur mukat na paae || fir mukat paae laag charanee satiguroo sabadh sunaae || kahai naanak veechaar dhekhahu vin satigur mukat na paae ||22||
One who turns away from the Guru, and becomes baymukh – without the True Guru, he shall not find liberation. He shall not find liberation anywhere else either; go and ask the wise ones about this. He shall wander through countless incarnations; without the True Guru, he shall not find liberation. But liberation is attained, when one is attached to the feet of the True Guru, chanting the Word of the Shabad. Says Nanak, contemplate this and see, that without the True Guru, there is no liberation. ||22||

aavahu sikh satiguroo ke piaariho gaavahu sachee baanee || baanee ta gaavahu guroo keree baaneeaa sir baanee || jin kau nadhar karam hovai hiradhai tinaa samaanee || peevahu a(n)mrit sadhaa rahahu har ra(n)g japih saarigapaanee || kahai naanak sadhaa gaavahu eh sachee baanee ||23||
Come, O beloved Sikhs of the True Guru, and sing the True Word of His Bani. Sing the Guru’s Bani, the supreme Word of Words. Those who are blessed by the Lord’s Glance of Grace – their hearts are imbued with this Bani. Drink in this Ambrosial Nectar, and remain in the Lord’s Love forever; meditate on the Lord, the Sustainer of the world. Says Nanak, sing this True Bani forever. ||23||

satiguroo binaa hor kachee hai baanee || baanee ta kachee satiguroo baajhahu hor kachee baanee || kahadhe kache sunadhe kache kacha(n)ee aakh vakhaanee || har har nit kareh rasanaa kahiaa kachhoo na jaanee || chit jin kaa hir liaa maiaa bolan pe ravaanee || kahai naanak satiguroo baajhahu hor kachee baanee ||24||
Without the True Guru, other songs are false. The songs are false without the True Guru; all other songs are false. The speakers are false, and the listeners are false; those who speak and recite are false. They may continually chant, ‘Har, Har’ with their tongues, but they do not know what they are saying. Their consciousness is lured by Maya; they are just reciting mechanically. Says Nanak, without the True Guru, other songs are false. ||24||

gur kaa sabadh rata(n)n hai heere jit jaRaau || sabadh ratan jit ma(n)n laagaa eh hoaa samaau || sabadh setee man miliaa sachai laiaa bhaau || aape heeraa ratan aape jis no dhei bujhai || kahai naanak sabadh ratan hai heeraa jit jaRaau ||25||
The Word of the Guru’s Shabad is a jewel, studded with diamonds. The mind which is attached to this jewel, merges into the Shabad. One whose mind is attuned to the Shabad, enshrines love for the True Lord. He Himself is the diamond, and He Himself is the jewel; one who is blessed, understands its value. Says Nanak, the Shabad is a jewel, studded with diamonds. ||25||

siv sakat aap upai kai karataa aape hukam varataae || hukam varataae aap vekhai gurmukh kisai bujhaae || toRe ba(n)dhan hovai mukat sabadh ma(n)n vasaae || gurmukh jis no aap kare su hovai ekas siau liv laae || kahai naanak aap karataa aape hukam bujhaae ||26||
He Himself created Shiva and Shakti, mind and matter; the Creator subjects them to His Command. Enforcing His Order, He Himself sees all. How rare are those who, as Gurmukh, come to know Him. They break their bonds, and attain liberation; they enshrine the Shabad within their minds. Those whom the Lord Himself makes Gurmukh, lovingly focus their consciousness on the One Lord. Says Nanak, He Himself is the Creator; He Himself reveals the Hukam of His Command. ||26||

simirat saasatr pu(n)n paap beechaaradhe tatai saar na jaanee || tatai saar na jaanee guroo baajhahu tatai saar na jaanee || tihee gunee sa(n)saar bhram sutaa sutiaa rain vihaanee || gur kirapaa te se jan jaage jinaa har man vasiaa boleh a(n)mirat baanee || kahai naanak so tat paae jis no anadhin har liv laagai jaagat rain vihaanee ||27||
The Simritees and the Shaastras discriminate between good and evil, but they do not know the true essence of reality. They do not know the true essence of reality without the Guru; they do not know the true essence of reality. The world is asleep in the three modes and doubt; it passes the night of its life sleeping. Those humble beings remain awake and aware, within whose minds, by Guru’s Grace, the Lord abides; they chant the Ambrosial Word of the Guru’s ni. Says Nanak, they alone obtain the essence of reality, who night and day remain lovingly absorbed in the lord; they pass the night of their life awake and aware.||27||

maataa ke udhar meh pratipaal kare so kiau manahu visaareeaai || manahu kiau visaareeaai evadd dhaataa jagan meh aahaar pahuchaave || os no kih poh na sakee jis nau aapanee liv laave || aapanee liv aape laae gurmukh sadhaa samaaleeaai || kahai naanak evadd dhaataa so kiau manahu visaareeaai ||28||
He nourished us in the mother’s womb; why forget Him from the mind? Why forget from the mind such a Great Giver, who gave us sustenance in the fire of the womb? Nothing can harm one, whom the Lord inspires to embrace His Love. He Himself is the love, and He Himself is the embrace; the Gurmukh contemplates Him forever. Says Nanak, why forget such a Great Giver from the mind? ||28||.

jaisee agan udhar meh taisee baahar maiaa || maiaa agan sabh iko jehee karatai khel rachaiaa || jaa tis bhaanaa taa ja(n)miaa paravaar bhalaa bhaiaa || liv chhuRakee lagee tirasanaa maiaa amar varataiaa || eh maiaa jit har visarai moh upajai bhaau dhoojaa laiaa || kahai naanak gur parasaadhee jinaa liv laagee tinee viche maiaa paiaa ||29||
As is the fire within the womb, so is Maya outside. The fire of Maya is one and the same; the Creator has staged this play. According to His Will, the child is born, and the family is very pleased. Love for the Lord wears off, and the child becomes. attached to desires; the script of Maya runs its course. This is Maya, by which the Lord is forgotten; emotional attachment and love of duality well up.Says Nanak,
by Guru’s Grace, those who enshrine love for the Lord find Him, in the midst of Maya.||29||

har aap amulak hai mul na paiaa jai || mul na paiaa jai kisai viTahu rahe lok vilalai || aaisaa satigur je milai tis no sir saupeeaai vichahu aap jai || jis dhaa jeeau tis mil rahai har vasai man aai || har aap amulak hai bhaag tinaa ke naanakaa jin har palai pai ||30||
The Lord Himself is priceless; His worth cannot be estimated. His worth cannot be estimated, even though people have grown weary of trying. If you meet such a True Guru, offer your head to Him; your selfishness and conceit will be eradicated from within. Your soul belongs to Him; remain united with Him, and the Lord will come to dwell in your mind. The Lord Himself is priceless; very fortunate are those, O Nanak, who attain to the Lord. ||30||

har raas meree man vanajaaraa || har raas meree man vanajaaraa satigur te raas jaanee || har har nit japih jeeahu laahaa khaTih dhihaaRee || eh dhan tinaa miliaa jin har aape bhaanaa || kahai naanak har raas meree man hoaa vanajaaraa ||31||
The Lord is my capital; my mind is the merchant. The Lord is my capital, and my mind is the merchant; through the True Guru, I know my capital. Meditate continually on the Lord, Har, Har, O my soul, and you shall collect your profits daily. This wealth is obtained by those who are pleasing to the Lord’s Will. Says Nanak, the Lord is my capital, and my mind is the merchant. ||31||

e rasanaa too an ras raach rahee teree piaas na jai || piaas na jai horat kitai jichar har ras palai na pai || har ras pai palai peeaai har ras bahuR na tirasanaa laagai aai || eh har ras karamee paieeaai satigur milai jis aai || kahai naanak hor an ras sabh veesare jaa har vasai man aai ||32||
O my tongue, you are engrossed in other tastes, but your thirsty desire is not quenched. Your thirst shall not be quenched by any means, until you attain the subtle essence of the Lord. If you do obtain the subtle essence of the Lord, and drink in this essence of the Lord, you shall not be troubled by desire again. This subtle essence of the Lord is obtained by good karma, when one comes to meet with the True Guru. Says Nanak, all other tastes and essences are forgotten, when the Lord comes to dwell within the mind.||32||

e sareeraa meriaa har tum meh jot rakhee taa too jag meh aaiaa || har jot rakhee tudh vich taa too jag meh aaiaa || har aape maataa aape pitaa jin jeeau upai jagat dhikhaiaa Il gur parasaadhee bujhiaa taa chalat hoaa chalat nadharee aaiaa || kahai naanak sirasaT kaa mool rachiaa jot raakhee taa too jag meh aaiaa || 33||
O my body, the Lord infused His Light into you, and then you came into the world. The Lord infused His Light into you, and then you came into the world. The Lord Himself is your mother, and He Himself is your father; He created the created beings, and revealed the world to them. By Guru’s Grace, some understand, and then it’s a show; it seems like just a show. Says Nanak, He laid the foundation of the Universe, and infused His Light, and then you came into the world. ||33||

man chaau bhiaa prabh aagam suniaa || har ma(n)gal gaau sakhee girahu ma(n)dhar baniaa || har gaau ma(n)gal nit sakhe’ee sog dhookh na viaape || gur charan laage dhin sabhaage aapanaa pir jaape || anahat baanee gur sabadh jaanee har naam har ras bhogo || kahai naanak prabh aap miliaa karan kaaran jogo ||34||
My mind has become joyful, hearing of God’s coming. Sing the songs of joy to welcome the Lord, O my companions; my household has become the Lord’s Mansion. Sing continually the songs of joy to welcome the Lord, O my companions, and sorrow and suffering will not afflict you. Blessed is that day, when I am attached to the Guru’s feet and meditate on my Husband Lord. I have come to know the unstruck sound current and the Word of the Guru’s Shabad; I enjoy the sublime essence of the Lord, the Lord’s Name. Says Nanak,God Himself has met me; He is the Deor, the Cause of causes. ||34||

e sareeraa meriaa is jag meh aai kai kiaa tudh karam kamaiaa || k karam kamaiaa tudh sareeraa jaa too jag meh aaiaa || jin har teraa rachan rachiaa so har man na vasaiaa Il gur parasaadhee har ma(n)n vasiaa poorab likhiaa paiaa || kahai naanak eh sareer paravaan hoaa jin satigur siau chit laiaa ||35||
O my body, why have you come into this world? What actions have you committed? And what actions have you committed, O my body, since you came into this world? The Lord who formed your form – you have not enshrined that Lord in your mind. By Guru’s Grace, the Lord abides within the mind, and one’s pre-ordained destiny is fulfilled. Says Nanak, this body is adorned and honored, when one’s consciousness is focused on the True Guru. ||35||

e netrahu meriho har tum meh jot dharee har bin avar na dhekhahu koiee || har bin avar na dhekhahu koiee nadharee har nihaaliaa || eh vis sa(n)saar tum dhekhadhe eh har kaa roop hai har roop nadharee aaiaa || gur parasaadhee bujhiaa jaa vekhaa har ik hai har bin avar na koiee || kahai naanak eh netr a(n)dh se satigur miliaai dhib dhirasaT hoiee ||36||
O my eyes, the Lord has infused His Light into you; do not look upon any other than the Lord. Do not look upon any other than the Lord; the Lord alone is worthy of beholding. This whole world which you see is the image of the Lord; only the image of the Lord is seen. By Guru’s Grace, I understand, and I see only the One Lord; there is no one except the Lord. Says Nanak, these eyes were blind; but meeting the True Guru, they became all-seeing.||36||

e sravanahu meriho saachai sunanai no paThaae || saachai sunanai no paThaae sareer laae sunahu sat baanee || jit sunee man tan hariaa hoaa rasanaa ras samaanee || sach alakh viddaanee taa kee gat kahee na jaae || kahai naanak a(n)mirat naam sunahu pavitr hovahu saachai sunanai no paThaae ||37||
O my ears, you were created only to hear the Truth. To hear the Truth, you were created and attached to the body; listen to the True Bani. Hearing it, the mind and body are rejuvenated, and the tongue is absorbed in Ambrosial Nectar. The True Lord is unseen and wondrous; His state cannot be described. Says Nanak, listen to the Ambrosial Naam and become holy; you were created only to hear the Truth. ||37||

har jeeau gufaa a(n)dhar rakh kai vaajaa pavan vajaiaa || vajaiaa vaajaa paun nau dhuaare paragaT ke’ee dhasavaa gupat rakhaiaa || gurdhuaarai lai bhaavanee ikanaa dhasavaa dhuaar dhikhaiaa || teh anek roop naau nav nidh tis dhaa a(n)t na jaiee paiaa || kahai naanak har piaarai jeeau gufaa a(n)dhar rakh kai vaajaa pavan vajaiaa ||38||
The Lord placed the soul to the cave of the body, and blew the breath of life into the musical instrument of the body. He blew the breath of life into the musical instrument of the body, and revealed the nine doors; but He kept the Tenth Door hidden.Through the Gurdwara, the Guru’s Gate, some are blessed with loving faith, and the Tenth Door is revealed to them. There are many images of the Lord, and the nine treasures of the Naam; His limits cannot be found. Says Nanak, the lord placed the soul to the cave of the body, and blew the breath of life into the musical instrument of the body.||38||

eh saachaa sohilaa saachai ghar gaavahu || gaavahu ta sohilaa ghar saachai jithai sadhaa sach dhiaavahe || sacho dhiaaveh jaa tudh bhaaveh gurmukh jinaa bujhaavahe || eih sach sabhanaa kaa khasam hai jis bakhase so jan paavahe || kahai naanak sach sohilaa sachai ghar gaavahe ||39||
Sing this true song of praise in the true home of your soul. Sing the song of praise in your true home; meditate there on the True Lord forever. They alone meditate on You, O True Lord, who are pleasing to Your Will; as Gurmukh, they understand. This Truth is the Lord and Master of all; whoever is blessed, obtains it. Says Nanak, sing the true song of praise in the true home of your soul. ||39||

anadh sunahu vaddabhaageeho sagal manorath poore || paarabraham prabh paiaa utare sagal visoore || dhookh rog sa(n)taap utare sunee sachee baanee || sa(n)t saajan bhe sarase poore gur te jaanee || sunate puneet kahate pavit satigur rahiaa bharapoore || binava(n)t naanak gur charan laage vaaje anahadh toore ||40||1||
Listen to the song of bliss, O most fortunate ones; all your longings shall be fulfilled. I have obtained the Supreme Lord God, and all sorrows have been forgotten. Pain, illness and suffering have departed, listening to the True Bani. The Saints and their friends are in ecstasy, knowing the Perfect Guru. Pure are the listeners, and pure are the speakers; the True Guru is all-pervading and permeating. Prays Nanak, touching the Guru’s Feet, the unstruck sound current of the celestial bugles vibrates and resounds. ||40||1|||

ਵਾਹਿਗੁਰੂ ਜੀ ਕਾ ਖਾਲਸਾ, ਵਾਹਿਗੁਰੂ ਜੀ ਕੀ ਫ਼ਤਿਹ!
""";
